name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  roave-backwards-compatibility-check:
    name: Roave Backwards Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set safe directory
        run: git config --global --add safe.directory /github/workspace
      - name: "Check for BC breaks"
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

          docker run --rm \
            -v "${GITHUB_WORKSPACE}":/github/workspace \
            -w /github/workspace \
            nyholm/roave-bc-check-ga
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["8.4", "8.3", "8.2", "8.1"]

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: touch .env

      - name: Set PHP version in .env
        run: |
          echo "PHP_COMPOSER=${{ matrix.php-version }}" >> .env
          echo "PHP_VERSION=${{ matrix.php-version }}" >> .env

      - name: Install dependencies (composer update) for PHP
        run: sh dock composer update

      - name: Run PHPUnit tests for PHP
        run: sh dock test